import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { questions } from '../src/data/index.js';
import { createApp } from '../server/app.js';
import { openDatabase } from '../server/database.js';
import { resolve } from 'node:path';
const database=openDatabase(':memory:');
const server=createApp({database,distDir:resolve('dist'),rateLimitEnabled:false}).listen(0,'127.0.0.1');
await new Promise(resolve=>server.once('listening',resolve));
const browser = await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const base=process.env.TEST_URL||`http://127.0.0.1:${server.address().port}`;
const errors=[];
const context=await browser.newContext({viewport:{width:1440,height:1100}});
const page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));
try{
  await page.goto(base);await page.getByRole('heading',{name:'Your next great score starts here.'}).waitFor();
  await page.screenshot({path:'/tmp/clause-overview.png',fullPage:true});
  await page.getByRole('button',{name:'Start practicing'}).click();
  await page.locator('.choice').nth(questions[0].answer).click();await page.getByRole('button',{name:'Check answer'}).click();
  await page.getByRole('heading',{name:'Nicely done.'}).waitFor();
  await page.getByRole('button',{name:'Bookmark question',exact:true}).click();
  await page.getByRole('button',{name:'Next question'}).click();
  assert.equal(await page.locator('.question-meta>span').innerText(),'QUESTION 2 OF 250');
  await page.locator('nav').getByRole('link',{name:'Rule library'}).click();
  await page.getByRole('heading',{name:'Good grammar is learnable.'}).waitFor();
  assert.equal(await page.locator('.lesson-tile').count(),25);
  await page.getByRole('textbox',{name:'Search rules'}).fill('Sentence boundaries');
  assert.ok(await page.locator('.lesson-tile').count()>=1);
  await page.locator('.lesson-tile').filter({has:page.getByRole('heading',{name:'Sentence boundaries',exact:true})}).click();await page.getByRole('button',{name:'Mark lesson complete'}).click();
  await page.getByRole('button',{name:'Lesson completed'}).waitFor();
  await page.locator('.top-signin').click();
  await page.getByRole('button',{name:'Create an account',exact:true}).click();
  const email=`browser-${Date.now()}@example.com`;
  await page.getByLabel('Your name').fill('Browser Learner');
  await page.getByLabel('Email address').fill(email);await page.getByLabel('Password', {exact:true}).fill('correct-horse-77');
  await page.getByRole('button',{name:'Create your account'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
  await page.waitForFunction(()=>document.querySelector('.sidebar-account small')?.textContent==='Progress synced');
  const second=await browser.newContext({viewport:{width:1280,height:900}});const other=await second.newPage();
  await other.goto(base);await other.locator('.top-signin').click();
  await other.getByLabel('Email address').fill(email);await other.getByLabel('Password',{exact:true}).fill('correct-horse-77');
  await other.getByRole('button',{name:'Sign in',exact:true}).last().click();await other.getByRole('dialog').waitFor({state:'hidden'});
  await other.locator('nav').getByRole('link',{name:'My progress'}).click();
  await other.getByRole('heading',{name:'Look how far you’re going.'}).waitFor();
  assert.equal(await other.locator('.progress-stats .stat').nth(1).locator('b').innerText(),'1');
  await other.locator('nav').getByRole('link',{name:'Rule library'}).click();
  await other.getByRole('heading',{name:'Good grammar is learnable.'}).waitFor();
  assert.equal(await other.locator('.completed-icon').count(),1);
  await second.close();
  await page.locator('nav').getByRole('link',{name:'Question Rush'}).click();
  await page.getByRole('button',{name:'Start Question Rush'}).click();
  assert.equal(await page.locator('.timer').innerText(),'15:00');
  await page.locator('.choice').first().click();await page.getByRole('button',{name:'Check answer'}).click();
  // Moving away from and back to an active round must preserve a checked answer.
  await page.locator('nav').getByRole('link',{name:'Overview'}).click();
  await page.locator('nav').getByRole('link',{name:'Question Rush'}).click();
  await page.getByRole('button',{name:'Next question'}).waitFor();
  await page.getByRole('button',{name:'Next question'}).click();
  await page.clock.install();await page.clock.fastForward(15*60*1000+1000);
  await page.getByText('YOUR RUSH RESULTS',{exact:true}).waitFor();
  assert.equal(await page.locator('.round-review details').count(),20);
  assert.equal(await page.locator('.results-stats>div').nth(2).locator('b').innerText(),'1');
  await context.close();
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const m=await mobile.newPage();
  await m.goto(base);await m.getByRole('heading',{name:'Your next great score starts here.'}).waitFor();
  assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile page overflows horizontally');
  await m.screenshot({path:'/tmp/clause-mobile.png',fullPage:true});
  await m.getByRole('button',{name:'Open navigation'}).click();
  await m.locator('nav').getByRole('link',{name:'Practice questions'}).click();
  await m.locator('.choice').first().waitFor();
  assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile practice overflows horizontally');
  await mobile.close();
  const full=await browser.newContext();const round=await full.newPage();
  await round.goto(`${base}/#rush`);await round.getByRole('button',{name:'Start Question Rush'}).click();
  const roundIds=new Set();
  for(let i=0;i<20;i++){
    const passage=await round.locator('.passage').innerText();
    const q=questions.find(q=>passage.startsWith(q.passage.split('___')[0]));
    assert.ok(q,`Question ${i+1} must exist in the bank`);assert.ok(!roundIds.has(q.id),'Rush must not repeat a question');roundIds.add(q.id);
    await round.locator('.choice').nth(q.answer).click();await round.getByRole('button',{name:'Check answer'}).click();
    await round.getByRole('heading',{name:'Nicely done.'}).waitFor();
    await round.getByRole('button',{name:i===19?'Finish round':'Next question',exact:true}).click();
  }
  await round.getByText('YOUR RUSH RESULTS',{exact:true}).waitFor();
  assert.equal(await round.locator('.rush-results>h2').innerText(),'20 / 20');
  assert.equal(await round.locator('.round-review details').count(),20);
  await full.close();
  assert.deepEqual(errors,[]);
  console.log('Browser checks passed: practice, explanations, bookmarks, lesson completion, registration, cross-browser sync, rush navigation/timeout, and mobile layouts.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));database.close();}
